function [stateDerivative,Tsingular,S,Sdot,Hamiltonian] = rocketDynamics_singular(epoch,in2,thrust,effectiveExhaustVelocity)
%rocketDynamics_singular
%    [stateDerivative,Tsingular,S,Sdot,Hamiltonian] = rocketDynamics_singular(EPOCH,IN2,THRUST,effectiveExhaustVelocity,RHO)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:00:26

height = in2(1,:);
lam1 = in2(4,:);
lam2 = in2(5,:);
lam3 = in2(6,:);
mass = in2(3,:);
velocity = in2(2,:);
t2 = velocity.^2;
t3 = velocity.^3;
t4 = 1.0./effectiveExhaustVelocity;
t5 = 1.0./height.^2;
t6 = 1.0./height.^3;
t7 = 1.0./mass;
t10 = 1.0./velocity;
t11 = height.*5.0e+2;
t16 = height.*1.0e+3;
t8 = t7.^2;
t9 = t7.^3;
t12 = t6.*2.0;
t13 = t10.*2.0;
t15 = -t11;
t17 = -t5;
t18 = -t16;
t19 = t4+t10;
t14 = lam1.*t8;
t20 = t15+5.0e+2;
t21 = t4+t13;
t23 = t18+1.0e+3;
t22 = exp(t20);
t24 = exp(t23);
t25 = t2.*t22.*3.1e+2;
t27 = t5.*t22.*velocity.*6.2e+2;
t28 = t3.*t22.*1.55e+5;
t30 = lam2.*t7.*t22.*velocity.*6.2e+2;
t33 = t2.*t7.*t22.*1.55e+5;
t34 = t3.*t7.*t24.*1.922e+5;
t36 = lam2.*t9.*t19.*t22.*velocity.*6.2e+2;
t38 = lam2.*t9.*t21.*t22.*velocity.*6.2e+2;
t40 = lam2.*t2.*t9.*t21.*t22.*6.2e+2;
t26 = -t25;
t29 = t7.*t25;
t31 = -t30;
t37 = t12+t33;
t41 = -t40;
t50 = t27+t28+t34;
t32 = lam1+t31;
t35 = t5+t29;
t39 = lam2.*t37;
t44 = t14+t41;
t51 = lam2.*t8.*t21.*t50;
t42 = t39-1.0;
t46 = t4.*t44;
t48 = lam2.*t8.*t19.*t22.*t35.*velocity.*6.2e+2;
t49 = t8.*t21.*t25.*t32;
t43 = t7.*t42;
t47 = -t46;
t45 = -t43;
t52 = t36+t38+t47;
t53 = 1.0./t52;
t54 = t45+t48+t49+t51;
t55 = t53.*t54;
stateDerivative = [velocity;t17-t7.*(t25-t55);-t4.*t55;-t42;-lam1+t30;-lam2.*t8.*(t25-t55)];
if nargout > 1
    Tsingular = t55;
end
if nargout > 2
    S = -lam3.*t4+lam2.*t7;
end
if nargout > 3
    Sdot = -lam1.*t7+lam2.*t8.*t21.*t25;
end
if nargout > 4
    Hamiltonian = -height-lam2.*(t5+t7.*(t25-thrust))+lam1.*velocity-lam3.*t4.*thrust;
end
